#!/bin/bash
#
# GROMACS MD simulation: anc_prors_cat + PRO
# Uses CHARMM36m + TIP3P
# 32 cores + GPU
#

set -e

GMX="/usr/local/gromacs/bin/gmx_mpi"
VINA_DIR="/storage/kiran-stuff/aaRS/phase2/energy_scoring/vina_182jobs"
WORK_DIR="/storage/kiran-stuff/aaRS/phase2/energy_scoring/gromacs_md_validation"

NAME="anc_prors_cat_PRO"
SYS_DIR="$WORK_DIR/systems/$NAME"
mkdir -p "$SYS_DIR"
cd "$SYS_DIR"

echo "============================================================"
echo "GROMACS MD: $NAME"
echo "Working directory: $SYS_DIR"
echo "============================================================"

# Copy MDP files
cp "$WORK_DIR/mdp"/*.mdp ./

# ============================================================
# Step 1: Prepare input structure
# ============================================================
echo ""
echo "Step 1: Preparing input structure..."

# Get complex from Vina
cp "$VINA_DIR/anc_prors_cat_PRO_PRO/complex.pdb" ./complex_input.pdb

# Separate protein (chain A) and ligand (chain B)
# Protein: all ATOM records from chain A
grep "^ATOM" complex_input.pdb > protein.pdb
echo "TER" >> protein.pdb
echo "END" >> protein.pdb

# Ligand: HETATM from chain B (the PRO amino acid)
grep "^HETATM" complex_input.pdb | grep " B " > ligand.pdb
echo "END" >> ligand.pdb

echo "  Protein atoms: $(grep -c '^ATOM' protein.pdb)"
echo "  Ligand atoms: $(grep -c '^HETATM' ligand.pdb)"

# ============================================================
# Step 2: Process protein with pdb2gmx
# ============================================================
echo ""
echo "Step 2: Processing protein with pdb2gmx (CHARMM36m)..."

$GMX pdb2gmx -f protein.pdb -o protein_processed.gro -p topol_protein.top \
    -i posre_protein.itp -water tip3p -ff charmm36m -ignh -his << EOF
0
0
0
EOF

# ============================================================
# Step 3: Process ligand with pdb2gmx
# ============================================================
echo ""
echo "Step 3: Processing ligand with pdb2gmx..."

# For amino acid ligand, treat as single-residue peptide with charged termini
$GMX pdb2gmx -f ligand.pdb -o ligand_processed.gro -p topol_ligand.top \
    -i posre_ligand.itp -water tip3p -ff charmm36m -ignh -ter << EOF
1
1
EOF

# ============================================================
# Step 4: Combine protein and ligand
# ============================================================
echo ""
echo "Step 4: Combining protein and ligand..."

# Get box size from protein
PROT_ATOMS=$(head -2 protein_processed.gro | tail -1)
LIG_ATOMS=$(head -2 ligand_processed.gro | tail -1)
TOTAL_ATOMS=$((PROT_ATOMS + LIG_ATOMS))

# Create combined structure
{
    head -1 protein_processed.gro  # Title
    echo " $TOTAL_ATOMS"
    # Protein coordinates (skip header, skip footer)
    sed -n '3,$p' protein_processed.gro | head -n -1
    # Ligand coordinates (skip header, skip footer)
    sed -n '3,$p' ligand_processed.gro | head -n -1
    # Box from protein
    tail -1 protein_processed.gro
} > complex.gro

# ============================================================
# Step 5: Create combined topology
# ============================================================
echo ""
echo "Step 5: Creating combined topology..."

# Extract protein moleculetype name
PROT_MOL=$(grep "^\[ moleculetype \]" -A 2 topol_protein.top | tail -1 | awk '{print $1}')
LIG_MOL=$(grep "^\[ moleculetype \]" -A 2 topol_ligand.top | tail -1 | awk '{print $1}')

cat > topol.top << TOPEOF
; Topology for $NAME
; Generated by GROMACS setup script

; Force field
#include "charmm36m.ff/forcefield.itp"

; Protein topology
$(grep -A 10000 "^\[ moleculetype \]" topol_protein.top | grep -v "^;" | head -n -10)

; Protein position restraints
#ifdef POSRES
#include "posre_protein.itp"
#endif

; Ligand topology
$(grep -A 10000 "^\[ moleculetype \]" topol_ligand.top | grep -v "^;" | head -n -10)

; Ligand position restraints
#ifdef POSRES_LIG
#include "posre_ligand.itp"
#endif

; Water
#include "charmm36m.ff/tip3p.itp"

; Ions
#include "charmm36m.ff/ions.itp"

[ system ]
$NAME

[ molecules ]
$PROT_MOL    1
$LIG_MOL     1
TOPEOF

# ============================================================
# Step 6: Create simulation box
# ============================================================
echo ""
echo "Step 6: Creating dodecahedron box (1.2 nm buffer)..."

$GMX editconf -f complex.gro -o boxed.gro -c -d 1.2 -bt dodecahedron

# ============================================================
# Step 7: Solvate
# ============================================================
echo ""
echo "Step 7: Solvating with TIP3P water..."

$GMX solvate -cp boxed.gro -cs spc216.gro -o solvated.gro -p topol.top

# ============================================================
# Step 8: Add ions (neutralize)
# ============================================================
echo ""
echo "Step 8: Adding ions..."

$GMX grompp -f minim.mdp -c solvated.gro -p topol.top -o ions.tpr -maxwarn 10
echo "SOL" | $GMX genion -s ions.tpr -o ionized.gro -p topol.top -pname NA -nname CL -neutral

# ============================================================
# Step 9: Create index file with Ligand group
# ============================================================
echo ""
echo "Step 9: Creating index file..."

# Create index with Protein, Ligand, Water_and_ions groups
{
    echo "q"
} | $GMX make_ndx -f ionized.gro -o index.ndx

# ============================================================
# Step 10: Energy minimization
# ============================================================
echo ""
echo "Step 10: Energy minimization..."

$GMX grompp -f minim.mdp -c ionized.gro -p topol.top -o em.tpr -maxwarn 10
$GMX mdrun -v -deffnm em -ntmpi 1 -ntomp 32

# Check EM success
echo "  Checking EM convergence..."
$GMX energy -f em.edr -o em_potential.xvg << EOF
Potential
EOF

# ============================================================
# Step 11: NVT equilibration (250 ps)
# ============================================================
echo ""
echo "Step 11: NVT equilibration (250 ps)..."

# Modify nvt.mdp for this system's groups
sed -e 's/tc-grps.*=.*/tc-grps = Protein non-Protein/' \
    -e 's/tau_t.*=.*/tau_t = 0.1 0.1/' \
    -e 's/ref_t.*=.*/ref_t = 300 300/' \
    nvt.mdp > nvt_run.mdp

$GMX grompp -f nvt_run.mdp -c em.gro -r em.gro -p topol.top -n index.ndx -o nvt.tpr -maxwarn 10
$GMX mdrun -v -deffnm nvt -ntmpi 1 -ntomp 32 -nb gpu -pme gpu

# ============================================================
# Step 12: NPT equilibration (500 ps)
# ============================================================
echo ""
echo "Step 12: NPT equilibration (500 ps)..."

# Modify npt.mdp for this system's groups
sed -e 's/tc-grps.*=.*/tc-grps = Protein non-Protein/' \
    -e 's/tau_t.*=.*/tau_t = 0.1 0.1/' \
    -e 's/ref_t.*=.*/ref_t = 300 300/' \
    npt.mdp > npt_run.mdp

$GMX grompp -f npt_run.mdp -c nvt.gro -r nvt.gro -p topol.top -n index.ndx -o npt.tpr -maxwarn 10
$GMX mdrun -v -deffnm npt -ntmpi 1 -ntomp 32 -nb gpu -pme gpu

# ============================================================
# Step 13: Production MD (5 ns)
# ============================================================
echo ""
echo "Step 13: Production MD (5 ns)..."

# Modify md.mdp for this system's groups
sed -e 's/tc-grps.*=.*/tc-grps = Protein non-Protein/' \
    -e 's/tau_t.*=.*/tau_t = 0.1 0.1/' \
    -e 's/ref_t.*=.*/ref_t = 300 300/' \
    md.mdp > md_run.mdp

$GMX grompp -f md_run.mdp -c npt.gro -p topol.top -n index.ndx -o md.tpr -maxwarn 10
$GMX mdrun -v -deffnm md -ntmpi 1 -ntomp 32 -nb gpu -pme gpu -bonded gpu

# ============================================================
# Analysis
# ============================================================
echo ""
echo "Step 14: Basic analysis..."

# RMSD of ligand
echo "Backbone Protein" | $GMX rms -s md.tpr -f md.xtc -o rmsd_protein.xvg -tu ns
echo "Protein Protein" | $GMX rms -s md.tpr -f md.xtc -o rmsd_ligand.xvg -tu ns

echo ""
echo "============================================================"
echo "COMPLETE: $NAME"
echo "============================================================"
echo ""
echo "Output files:"
echo "  - md.gro: Final structure"
echo "  - md.xtc: Trajectory"
echo "  - rmsd_*.xvg: RMSD analysis"
